//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfDemos.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int PositionId { get; set; }
        public System.DateTime ReportedAt { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public int CruiseId { get; set; }
    
        public virtual Cruise Cruise { get; set; }
    }
}
