//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPlay01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PositionsEntities : DbContext
    {
        public PositionsEntities()
            : base("name=PositionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cruise> Cruises { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
    }
}
