//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPlay01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int PlaceID { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string AdminCode { get; set; }
        public string AdminName { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
    }
}
