//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/13/2013 1:17:20 AM
namespace EFDemos.WcfDataClient.PositionsService
{
    
    /// <summary>
    /// There are no comments for PositionsContext in the schema.
    /// </summary>
    public partial class PositionsContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PositionsContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PositionsContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "PositionsModel", "EFDemos.WcfDataClient.PositionsService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("EFDemos.WcfDataClient.PositionsService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("PositionsModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Cruises in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Cruise> Cruises
        {
            get
            {
                if ((this._Cruises == null))
                {
                    this._Cruises = base.CreateQuery<Cruise>("Cruises");
                }
                return this._Cruises;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Cruise> _Cruises;
        /// <summary>
        /// There are no comments for Places in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Place> Places
        {
            get
            {
                if ((this._Places == null))
                {
                    this._Places = base.CreateQuery<Place>("Places");
                }
                return this._Places;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Place> _Places;
        /// <summary>
        /// There are no comments for Positions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Position> Positions
        {
            get
            {
                if ((this._Positions == null))
                {
                    this._Positions = base.CreateQuery<Position>("Positions");
                }
                return this._Positions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Position> _Positions;
        /// <summary>
        /// There are no comments for TimeZones in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TimeZone> TimeZones
        {
            get
            {
                if ((this._TimeZones == null))
                {
                    this._TimeZones = base.CreateQuery<TimeZone>("TimeZones");
                }
                return this._TimeZones;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TimeZone> _TimeZones;
        /// <summary>
        /// There are no comments for Cruises in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCruises(Cruise cruise)
        {
            base.AddObject("Cruises", cruise);
        }
        /// <summary>
        /// There are no comments for Places in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPlaces(Place place)
        {
            base.AddObject("Places", place);
        }
        /// <summary>
        /// There are no comments for Positions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPositions(Position position)
        {
            base.AddObject("Positions", position);
        }
        /// <summary>
        /// There are no comments for TimeZones in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTimeZones(TimeZone timeZone)
        {
            base.AddObject("TimeZones", timeZone);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"PositionsModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\">" +
                "<EntityType Name=\"Cruise\"><Key><PropertyRef Name=\"CruiseID\" /></Key><Property Na" +
                "me=\"CruiseID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Ed" +
                "m.String\" /><Property Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Sta" +
                "rtDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"EndDate\" Type=\"Ed" +
                "m.DateTime\" /><Property Name=\"CurrentTrip\" Type=\"Edm.Boolean\" Nullable=\"false\" /" +
                "><NavigationProperty Name=\"Positions\" Relationship=\"PositionsModel.Cruise_Positi" +
                "ons_Position_Cruise\" ToRole=\"Position_Cruise\" FromRole=\"Cruise_Positions\" /></En" +
                "tityType><EntityType Name=\"Place\"><Key><PropertyRef Name=\"PlaceID\" /></Key><Prop" +
                "erty Name=\"PlaceID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CountryC" +
                "ode\" Type=\"Edm.String\" /><Property Name=\"CountryName\" Type=\"Edm.String\" /><Prope" +
                "rty Name=\"AdminCode\" Type=\"Edm.String\" /><Property Name=\"AdminName\" Type=\"Edm.St" +
                "ring\" /><NavigationProperty Name=\"Positions\" Relationship=\"PositionsModel.Place_" +
                "Positions_Position_Place\" ToRole=\"Position_Place\" FromRole=\"Place_Positions\" /><" +
                "/EntityType><EntityType Name=\"Position\"><Key><PropertyRef Name=\"PositionID\" /></" +
                "Key><Property Name=\"PositionID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Na" +
                "me=\"ReportedAt\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Latitude\"" +
                " Type=\"Edm.Single\" /><Property Name=\"Longitude\" Type=\"Edm.Single\" /><Property Na" +
                "me=\"DistanceFromLast\" Type=\"Edm.Single\" Nullable=\"false\" /><Property Name=\"Cruis" +
                "eID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"PlaceID\" Type=\"Edm.Int3" +
                "2\" /><Property Name=\"TimeZoneID\" Type=\"Edm.Int32\" /><NavigationProperty Name=\"Cr" +
                "uise\" Relationship=\"PositionsModel.Cruise_Positions_Position_Cruise\" ToRole=\"Cru" +
                "ise_Positions\" FromRole=\"Position_Cruise\" /><NavigationProperty Name=\"Place\" Rel" +
                "ationship=\"PositionsModel.Place_Positions_Position_Place\" ToRole=\"Place_Position" +
                "s\" FromRole=\"Position_Place\" /><NavigationProperty Name=\"TimeZone\" Relationship=" +
                "\"PositionsModel.Position_TimeZone_TimeZone_Positions\" ToRole=\"TimeZone_Positions" +
                "\" FromRole=\"Position_TimeZone\" /></EntityType><EntityType Name=\"TimeZone\"><Key><" +
                "PropertyRef Name=\"TimeZoneID\" /></Key><Property Name=\"TimeZoneID\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><Property Name=\"TimeZoneName\" Type=\"Edm.String\" /><Propert" +
                "y Name=\"GMTOffset\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property Name=\"DSTOffs" +
                "et\" Type=\"Edm.Decimal\" Nullable=\"false\" /><NavigationProperty Name=\"Positions\" R" +
                "elationship=\"PositionsModel.Position_TimeZone_TimeZone_Positions\" ToRole=\"Positi" +
                "on_TimeZone\" FromRole=\"TimeZone_Positions\" /></EntityType><Association Name=\"Cru" +
                "ise_Positions_Position_Cruise\"><End Type=\"PositionsModel.Position\" Role=\"Positio" +
                "n_Cruise\" Multiplicity=\"*\" /><End Type=\"PositionsModel.Cruise\" Role=\"Cruise_Posi" +
                "tions\" Multiplicity=\"0..1\" /></Association><Association Name=\"Place_Positions_Po" +
                "sition_Place\"><End Type=\"PositionsModel.Position\" Role=\"Position_Place\" Multipli" +
                "city=\"*\" /><End Type=\"PositionsModel.Place\" Role=\"Place_Positions\" Multiplicity=" +
                "\"0..1\" /></Association><Association Name=\"Position_TimeZone_TimeZone_Positions\">" +
                "<End Type=\"PositionsModel.TimeZone\" Role=\"TimeZone_Positions\" Multiplicity=\"0..1" +
                "\" /><End Type=\"PositionsModel.Position\" Role=\"Position_TimeZone\" Multiplicity=\"*" +
                "\" /></Association></Schema><Schema Namespace=\"EFDemos.WcfDataSvc\" xmlns=\"http://" +
                "schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"PositionsContext\" " +
                "m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Cruises\" EntityType=\"Position" +
                "sModel.Cruise\" /><EntitySet Name=\"Places\" EntityType=\"PositionsModel.Place\" /><E" +
                "ntitySet Name=\"Positions\" EntityType=\"PositionsModel.Position\" /><EntitySet Name" +
                "=\"TimeZones\" EntityType=\"PositionsModel.TimeZone\" /><AssociationSet Name=\"FK_Pos" +
                "itions_Cruises\" Association=\"PositionsModel.Cruise_Positions_Position_Cruise\"><E" +
                "nd Role=\"Cruise_Positions\" EntitySet=\"Cruises\" /><End Role=\"Position_Cruise\" Ent" +
                "itySet=\"Positions\" /></AssociationSet><AssociationSet Name=\"FK_Positions_Places\"" +
                " Association=\"PositionsModel.Place_Positions_Position_Place\"><End Role=\"Place_Po" +
                "sitions\" EntitySet=\"Places\" /><End Role=\"Position_Place\" EntitySet=\"Positions\" /" +
                "></AssociationSet><AssociationSet Name=\"FK_Positions_TimeZones\" Association=\"Pos" +
                "itionsModel.Position_TimeZone_TimeZone_Positions\"><End Role=\"Position_TimeZone\" " +
                "EntitySet=\"Positions\" /><End Role=\"TimeZone_Positions\" EntitySet=\"TimeZones\" /><" +
                "/AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for PositionsModel.Cruise in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CruiseID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Cruises")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CruiseID")]
    public partial class Cruise : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Cruise object.
        /// </summary>
        /// <param name="cruiseID">Initial value of CruiseID.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="currentTrip">Initial value of CurrentTrip.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Cruise CreateCruise(int cruiseID, global::System.DateTime startDate, bool currentTrip)
        {
            Cruise cruise = new Cruise();
            cruise.CruiseID = cruiseID;
            cruise.StartDate = startDate;
            cruise.CurrentTrip = currentTrip;
            return cruise;
        }
        /// <summary>
        /// There are no comments for Property CruiseID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CruiseID
        {
            get
            {
                return this._CruiseID;
            }
            set
            {
                this.OnCruiseIDChanging(value);
                this._CruiseID = value;
                this.OnCruiseIDChanged();
                this.OnPropertyChanged("CruiseID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CruiseID;
        partial void OnCruiseIDChanging(int value);
        partial void OnCruiseIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this._EndDate = value;
                this.OnEndDateChanged();
                this.OnPropertyChanged("EndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property CurrentTrip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool CurrentTrip
        {
            get
            {
                return this._CurrentTrip;
            }
            set
            {
                this.OnCurrentTripChanging(value);
                this._CurrentTrip = value;
                this.OnCurrentTripChanged();
                this.OnPropertyChanged("CurrentTrip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _CurrentTrip;
        partial void OnCurrentTripChanging(bool value);
        partial void OnCurrentTripChanged();
        /// <summary>
        /// There are no comments for Positions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Position> Positions
        {
            get
            {
                return this._Positions;
            }
            set
            {
                this._Positions = value;
                this.OnPropertyChanged("Positions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Position> _Positions = new global::System.Data.Services.Client.DataServiceCollection<Position>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PositionsModel.Place in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlaceID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Places")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PlaceID")]
    public partial class Place : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Place object.
        /// </summary>
        /// <param name="placeID">Initial value of PlaceID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Place CreatePlace(int placeID)
        {
            Place place = new Place();
            place.PlaceID = placeID;
            return place;
        }
        /// <summary>
        /// There are no comments for Property PlaceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PlaceID
        {
            get
            {
                return this._PlaceID;
            }
            set
            {
                this.OnPlaceIDChanging(value);
                this._PlaceID = value;
                this.OnPlaceIDChanged();
                this.OnPropertyChanged("PlaceID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PlaceID;
        partial void OnPlaceIDChanging(int value);
        partial void OnPlaceIDChanged();
        /// <summary>
        /// There are no comments for Property CountryCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CountryCode
        {
            get
            {
                return this._CountryCode;
            }
            set
            {
                this.OnCountryCodeChanging(value);
                this._CountryCode = value;
                this.OnCountryCodeChanged();
                this.OnPropertyChanged("CountryCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CountryCode;
        partial void OnCountryCodeChanging(string value);
        partial void OnCountryCodeChanged();
        /// <summary>
        /// There are no comments for Property CountryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CountryName
        {
            get
            {
                return this._CountryName;
            }
            set
            {
                this.OnCountryNameChanging(value);
                this._CountryName = value;
                this.OnCountryNameChanged();
                this.OnPropertyChanged("CountryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CountryName;
        partial void OnCountryNameChanging(string value);
        partial void OnCountryNameChanged();
        /// <summary>
        /// There are no comments for Property AdminCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AdminCode
        {
            get
            {
                return this._AdminCode;
            }
            set
            {
                this.OnAdminCodeChanging(value);
                this._AdminCode = value;
                this.OnAdminCodeChanged();
                this.OnPropertyChanged("AdminCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AdminCode;
        partial void OnAdminCodeChanging(string value);
        partial void OnAdminCodeChanged();
        /// <summary>
        /// There are no comments for Property AdminName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AdminName
        {
            get
            {
                return this._AdminName;
            }
            set
            {
                this.OnAdminNameChanging(value);
                this._AdminName = value;
                this.OnAdminNameChanged();
                this.OnPropertyChanged("AdminName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AdminName;
        partial void OnAdminNameChanging(string value);
        partial void OnAdminNameChanged();
        /// <summary>
        /// There are no comments for Positions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Position> Positions
        {
            get
            {
                return this._Positions;
            }
            set
            {
                this._Positions = value;
                this.OnPropertyChanged("Positions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Position> _Positions = new global::System.Data.Services.Client.DataServiceCollection<Position>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PositionsModel.Position in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PositionID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Positions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PositionID")]
    public partial class Position : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Position object.
        /// </summary>
        /// <param name="positionID">Initial value of PositionID.</param>
        /// <param name="reportedAt">Initial value of ReportedAt.</param>
        /// <param name="distanceFromLast">Initial value of DistanceFromLast.</param>
        /// <param name="cruiseID">Initial value of CruiseID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Position CreatePosition(int positionID, global::System.DateTime reportedAt, float distanceFromLast, int cruiseID)
        {
            Position position = new Position();
            position.PositionID = positionID;
            position.ReportedAt = reportedAt;
            position.DistanceFromLast = distanceFromLast;
            position.CruiseID = cruiseID;
            return position;
        }
        /// <summary>
        /// There are no comments for Property PositionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PositionID
        {
            get
            {
                return this._PositionID;
            }
            set
            {
                this.OnPositionIDChanging(value);
                this._PositionID = value;
                this.OnPositionIDChanged();
                this.OnPropertyChanged("PositionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PositionID;
        partial void OnPositionIDChanging(int value);
        partial void OnPositionIDChanged();
        /// <summary>
        /// There are no comments for Property ReportedAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ReportedAt
        {
            get
            {
                return this._ReportedAt;
            }
            set
            {
                this.OnReportedAtChanging(value);
                this._ReportedAt = value;
                this.OnReportedAtChanged();
                this.OnPropertyChanged("ReportedAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ReportedAt;
        partial void OnReportedAtChanging(global::System.DateTime value);
        partial void OnReportedAtChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<float> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("Latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<float> _Latitude;
        partial void OnLatitudeChanging(global::System.Nullable<float> value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<float> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("Longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<float> _Longitude;
        partial void OnLongitudeChanging(global::System.Nullable<float> value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Property DistanceFromLast in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float DistanceFromLast
        {
            get
            {
                return this._DistanceFromLast;
            }
            set
            {
                this.OnDistanceFromLastChanging(value);
                this._DistanceFromLast = value;
                this.OnDistanceFromLastChanged();
                this.OnPropertyChanged("DistanceFromLast");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _DistanceFromLast;
        partial void OnDistanceFromLastChanging(float value);
        partial void OnDistanceFromLastChanged();
        /// <summary>
        /// There are no comments for Property CruiseID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CruiseID
        {
            get
            {
                return this._CruiseID;
            }
            set
            {
                this.OnCruiseIDChanging(value);
                this._CruiseID = value;
                this.OnCruiseIDChanged();
                this.OnPropertyChanged("CruiseID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CruiseID;
        partial void OnCruiseIDChanging(int value);
        partial void OnCruiseIDChanged();
        /// <summary>
        /// There are no comments for Property PlaceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> PlaceID
        {
            get
            {
                return this._PlaceID;
            }
            set
            {
                this.OnPlaceIDChanging(value);
                this._PlaceID = value;
                this.OnPlaceIDChanged();
                this.OnPropertyChanged("PlaceID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _PlaceID;
        partial void OnPlaceIDChanging(global::System.Nullable<int> value);
        partial void OnPlaceIDChanged();
        /// <summary>
        /// There are no comments for Property TimeZoneID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> TimeZoneID
        {
            get
            {
                return this._TimeZoneID;
            }
            set
            {
                this.OnTimeZoneIDChanging(value);
                this._TimeZoneID = value;
                this.OnTimeZoneIDChanged();
                this.OnPropertyChanged("TimeZoneID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _TimeZoneID;
        partial void OnTimeZoneIDChanging(global::System.Nullable<int> value);
        partial void OnTimeZoneIDChanged();
        /// <summary>
        /// There are no comments for Cruise in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Cruise Cruise
        {
            get
            {
                return this._Cruise;
            }
            set
            {
                this._Cruise = value;
                this.OnPropertyChanged("Cruise");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Cruise _Cruise;
        /// <summary>
        /// There are no comments for Place in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Place Place
        {
            get
            {
                return this._Place;
            }
            set
            {
                this._Place = value;
                this.OnPropertyChanged("Place");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Place _Place;
        /// <summary>
        /// There are no comments for TimeZone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TimeZone TimeZone
        {
            get
            {
                return this._TimeZone;
            }
            set
            {
                this._TimeZone = value;
                this.OnPropertyChanged("TimeZone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private TimeZone _TimeZone;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PositionsModel.TimeZone in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TimeZoneID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TimeZones")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TimeZoneID")]
    public partial class TimeZone : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TimeZone object.
        /// </summary>
        /// <param name="timeZoneID">Initial value of TimeZoneID.</param>
        /// <param name="gMTOffset">Initial value of GMTOffset.</param>
        /// <param name="dSTOffset">Initial value of DSTOffset.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TimeZone CreateTimeZone(int timeZoneID, decimal gMTOffset, decimal dSTOffset)
        {
            TimeZone timeZone = new TimeZone();
            timeZone.TimeZoneID = timeZoneID;
            timeZone.GMTOffset = gMTOffset;
            timeZone.DSTOffset = dSTOffset;
            return timeZone;
        }
        /// <summary>
        /// There are no comments for Property TimeZoneID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TimeZoneID
        {
            get
            {
                return this._TimeZoneID;
            }
            set
            {
                this.OnTimeZoneIDChanging(value);
                this._TimeZoneID = value;
                this.OnTimeZoneIDChanged();
                this.OnPropertyChanged("TimeZoneID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TimeZoneID;
        partial void OnTimeZoneIDChanging(int value);
        partial void OnTimeZoneIDChanged();
        /// <summary>
        /// There are no comments for Property TimeZoneName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TimeZoneName
        {
            get
            {
                return this._TimeZoneName;
            }
            set
            {
                this.OnTimeZoneNameChanging(value);
                this._TimeZoneName = value;
                this.OnTimeZoneNameChanged();
                this.OnPropertyChanged("TimeZoneName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TimeZoneName;
        partial void OnTimeZoneNameChanging(string value);
        partial void OnTimeZoneNameChanged();
        /// <summary>
        /// There are no comments for Property GMTOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal GMTOffset
        {
            get
            {
                return this._GMTOffset;
            }
            set
            {
                this.OnGMTOffsetChanging(value);
                this._GMTOffset = value;
                this.OnGMTOffsetChanged();
                this.OnPropertyChanged("GMTOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _GMTOffset;
        partial void OnGMTOffsetChanging(decimal value);
        partial void OnGMTOffsetChanged();
        /// <summary>
        /// There are no comments for Property DSTOffset in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal DSTOffset
        {
            get
            {
                return this._DSTOffset;
            }
            set
            {
                this.OnDSTOffsetChanging(value);
                this._DSTOffset = value;
                this.OnDSTOffsetChanged();
                this.OnPropertyChanged("DSTOffset");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _DSTOffset;
        partial void OnDSTOffsetChanging(decimal value);
        partial void OnDSTOffsetChanged();
        /// <summary>
        /// There are no comments for Positions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Position> Positions
        {
            get
            {
                return this._Positions;
            }
            set
            {
                this._Positions = value;
                this.OnPropertyChanged("Positions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Position> _Positions = new global::System.Data.Services.Client.DataServiceCollection<Position>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
