//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemos.WcfDataSvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public TimeZone()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int TimeZoneID { get; set; }
        public string TimeZoneName { get; set; }
        public decimal GMTOffset { get; set; }
        public decimal DSTOffset { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
    }
}
